### ISSUE TITLE
build broken on case-insensitive filesystems

### ISSUE THREAD

**Issue by veprbl** [MCredstoner2004/ImageLOL#1]
On systems like macOS the build may fail with an error:
```
[100%] Linking CXX executable ImageLOL
ld: can't open output file for writing: ImageLOL, errno=21 for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
This is because of the directory imagelol conflicting with the name of the ImageLOL executable. Would you consider renaming that directory to "src"?

**Comment by MCredstoner2004** [comment]
Are you building this in the main folder of the repo?
can you try building from a build dir instead, I think that should have no issues, In source build should be discouraged anyways

**Comment by veprbl** [comment]
IIRC the conflict occurs inside the build directory between the "imagelol" directory (holding the object files?) and the "ImageLOL" executable file.

**Comment by MCredstoner2004** [comment]
Ah, I see, you're right, I'm working on a relatively big commit right now and I could add it on that, but it could take a while, do you need this to be fixed right now or can you wait a few more days?

**Comment by MCredstoner2004** [comment]
okay, I changed the name of the ImageLOL directory, does that part work now?, I don't have access to a macos system and the CI failed on a zlib issue

**Comment by veprbl** [comment]
Builds fine for me with
```
nix-build -I nixpkgs=channel:nixpkgs-unstable -E 'with import <nixpkgs> {}; imagelol.overrideAttrs (prev: { src = (builtins.fetchGit { url = https://github.com/MCredstoner2004/ImageLOL.git; submodules = true; }).outPath; postPatch = ":"; buildInputs = prev.buildInputs or [] ++ [ zlib ]; })'
```

Thanks!
